
export const WS_PERS_CONNECTION_START: 'WS_PERS_CONNECTION_START' = 'WS_PERS_CONNECTION_START';
export const WS_PERS_CONNECTION_SUCCESS: 'WS_PERS_CONNECTION_SUCCESS' = 'WS_PERS_CONNECTION_SUCCESS'; 
export const WS_PERS_CONNECTION_ERROR: 'WS_PERS_CONNECTION_ERROR' = 'WS_PERS_CONNECTION_ERROR';
export const WS_PERS_CONNECTION_CLOSED: 'WS_PERS_CONNECTION_CLOSED' = 'WS_PERS_CONNECTION_CLOSED';
export const WS_PERS_GET_MESSAGE: 'WS_PERS_GET_MESSAGE' = 'WS_PERS_GET_MESSAGE';
export const WS_PERS_SEND_MESSAGE: 'WS_PERS_SEND_MESSAGE' = 'WS_PERS_SEND_MESSAGE';
export const WS_PERS_CLEAR_ORDERS: 'WS_PERS_CLEAR_ORDERS' = 'WS_PERS_CLEAR_ORDERS';
export const WS_PERS_CONNECTION_CLOSE: 'WS_PERS_CONNECTION_CLOSE' = 'WS_PERS_CONNECTION_CLOSE';


